server:
  port: 8888

eureka:
  instance:
    hostname: nood-config
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://nodd-discovery:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jackelee1990/nood-config-repo