server:
  port: 8761


eureka:
  instance:
    hostname: nood-discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://nood-discovery:${server.port}/eureka/

spring.cloud.config.discovery.enabled: true