server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 60
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 30000
    renewalPercentThreshold: 0.49
    renewalThresholdUpdateIntervalMs: 10000
    peer-eureka-nodes-update-interval-ms: 10000
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000
spring:
  security:
    user:
      name: admin
      password: admin


