info:
  name: nood-center
  author: singh
  description: 注册中心

server:
  port: 8761
  tomcat:
    uri-encoding: UTF-8

logging:
  path: logs
  level:
    root: INFO

eureka:
  dashboard:
    enabled: true
  server:
    enable-self-preservation: false # 关闭自我保护
    peer-eureka-nodes-update-interval-ms: 10000
    peer-node-read-timeout-ms: 10000
    wait-time-in-ms-when-sync-empty: 0
    renewal-threshold-update-interval-ms: 10000
  instance:
    preferIpAddress: true
    status-page-url-path: /swagger-ui.html
  client:
    fetch-registry: false
    register-with-eureka: false
    registry-fetch-interval-seconds: 30
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/





