info:
  name: nood-center
  author: singh
  description: 注册中心

server:
  port: 8761
  tomcat:
    uri-encoding: UTF-8

logging:
  path: logs
  level:
    root: INFO

eureka:
  dashboard:
    enabled: true
  server:
    enableSelfPreservation: false # 关闭自我保护
    waitTimeInMsWhenSyncEmpty: 30000
    renewalPercentThreshold: 0.49
    renewalThresholdUpdateIntervalMs: 10000
    peer-eureka-nodes-update-interval-ms: 10000
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false #false:不作为一个客户端注册到注册中心
    fetchRegistry: false  #为true时，可以启动，但报异常：Cannot execute




