server:
  port: 8761

eureka:
  instance:
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ipAddress}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 30000
    renewalPercentThreshold: 0.49
    renewalThresholdUpdateIntervalMs: 10000
    peer-eureka-nodes-update-interval-ms: 10000

