info:
  description: 配置服务

server:
  port: 8762
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    root: INFO

#spring:
#   profiles:
#      active: native
#   cloud:
#      config:
#         server:
#            native:
#              search-locations: E:/GitHub/myproject/nood-config-repo

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/singhlee/nood-config-repo.git
          username: singhlee
          password: E~60ACEKS04toY

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
