info:
  description: 配置服务

server:
  port: 8762
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    root: INFO

#spring:
#   profiles:
#      active: native
#   cloud:
#      config:
#         server:
#            native:
#              search-locations: E:/GitHub/myproject/nood-config-repo

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/singhlee/nood-config-repo.git
          username: singhlee
          password: E~60ACEKS04toY
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        hostname: 172.16.10.112
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        tags: urlprefix-/${spring.application.name}
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}


#eureka:
#  instance:
#    prefer-ip-address: true
#    ip-address: ${spring.cloud.client.ip-address}:${server.port}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone : http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
